[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "cogs"}

[tool.setuptools.packages.find]
where = ["cogs"]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]